### ISSUE TITLE
Features?

### ISSUE THREAD

**Issue by ghost** [Grarak/KernelAdiutor#177]
It would be awesome if you could ad these
1. Change govenors of each individual core
2. A small screen overlay of cpu frequency and whitch cores are actave and mabie an option to toogle them like in the app
3. A file browser would be cool!

These features would be awesome!
Thanks for a great app.

**Comment by Cardinal97** [comment]
The first feature dont make sense because the other cores are dependent on the parent core..so its always according to the parent core...plus u cant set anythin when the core is in deepsleep...

And the second thing u asked is already there....go see cpu fragment....

The third feature...Why do u want it?? Is that anyway relevent to kernel??? It makes the app bigger...U hav file browser to flash kernel and recovery....

**Comment by RenderBroken** [comment]
First feature is possible with MSM_Limiter but someone already created a ticket for it. 2 and 3 seem to not fit with the design of the App but I am not the creator.

**Comment by gtlukegt** [comment]
Ignore 3 but with 1 ive seen other apps that are able to change the govenor for each core.

**Comment by Cardinal97** [comment]
If it is as said by renderbroken....i.e MSM_Limiter ...Issue has been already opened....
