### ISSUE TITLE
Mako Hotplug Controls

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#21]
Can you add control for mako hotplug from franco? I will give the paths if needed, I just need to look into it a bit more on my side, I will add them here if required once I find them.

Thanks in advance, you are doing an amazing job:)

**Comment by RIPng** [comment]
Path is /sys/devices/virtual/misc/mako_hotplug_control/cpufreq_unplug_limit
/sys/devices/virtual/misc/mako_hotplug_control/high_load_counter
/sys/devices/virtual/misc/mako_hotplug_control/load_threshold
/sys/devices/virtual/misc/mako_hotplug_control/max_load_counter
/sys/devices/virtual/misc/mako_hotplug_control/min_time_cpu_online
/sys/devices/virtual/misc/mako_hotplug_control/timer

**Comment by RIPng** [comment]
Here is what each value does from the franco kernel FAQ XDA thread.

/* 
 * system load threshold to decide when online or offline cores 
 * from 0 to 100
 */
unsigned int load_threshold;

/* 
 * counter to filter online/offline calls. The load needs to be above
 * load_threshold X high_load_counter times for the cores to go online
 * otherwise they stay offline
 */
unsigned int high_load_counter;

/* 
 * max number of samples counters allowed to be counted. The higher the
 * value the longer it will take the driver to offline cores after a period
 * of high and continuous load
 */
unsigned int max_load_counter;

/* 
 * if the current CPU freq is above this limit don't offline the cores 
 * for a couple of extra samples
 */
unsigned int cpufreq_unplug_limit;

/* 
 * minimum time in seconds that a core stays online to avoid too many
 * online/offline calls
 */
unsigned int min_time_cpu_online;

/* 
 * sample timer in seconds. The default value of 1 equals to 10 samples
 * every second. The higher the value the less samples per second it runs
 */
         unsigned int timer;

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/ce0135a39479d9aaadcc319c49829044b380b427
