### ISSUE TITLE
GPU load in GPUFreq.java

### ISSUE THREAD

**Issue by waterdaan** [Grarak/KernelAdiutor#450]
int length = value.split(" ").length;

on onePlusOne if the GPU is in use length=3, if not in use length = 14
so value.split(" ")[0]=""

this is working on 1+1

public static int getBusy() {
        String value = Utils.readFile(BUSY);
        float arg1 = Utils.strToFloat(value.split(" ")[1]);
        float arg2 = Utils.strToFloat(value.split(" ")[2]);
        return arg2 == 0 ? 0 : Math.round(arg1 / arg2 * 100f);
    }

**Comment by waterdaan** [comment]
nevermind I must have been licking too many a frogs

**Comment by hzhongmin** [comment]
Hello 
Could you tell how to get GPU load in the app, is read from sysfs? if so , could you share the path ?

Thanks.

**Comment by fgl27** [comment]
@hzhongmin 

you can find paths by reading the source files of this repo

https://github.com/Grarak/KernelAdiutor/blob/master/app/src/main/java/com/grarak/kerneladiutor/utils/kernel/gpu/GPUFreq.java#L56

@waterdaan

you was right.

that is because spacing formatting done by the driver, it puts extra spaces before and after the first value when the value is not full, one can easily see it by cat, result as see bellow "full of spaces":

	# cat /sys/class/kgsl/kgsl-3d0/gpubusy
	      0       0

instead of

	    public int getBusy() {
		String value = Utils.readFile(BUSY);
		float arg1 = Utils.strToFloat(value.split(" ")[0]);
		float arg2 = Utils.strToFloat(value.split(" ")[1]);
		return arg2 == 0 ? 0 : Math.round(arg1 / arg2 * 100f);
	    }

One must do

	    public int getBusy() {
		String[] value = Utils.readFile(BUSY).trim().split("\\s+");
		if (value.length == 2) {

		    float arg1 = Float.valueOf(value[0]);
		    float arg2 = Float.valueOf(value[1]);

		     arg2 == 0 ? 0 : Math.round(arg1 / arg2 * 100f);
	        } else return 0;
	    }

@Grarak just in case you wanna to fix it
