### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by nazar-pc** [Grarak/KernelAdiutor#545]
Since this app is Open Source, would be nice to have it on F-Droid eventually. Is it possible?

**Comment by guest4711** [comment]
It's allready there (but in archive): Kernel Adiutor (Manage kernel parameters) - https://f-droid.org/app/com.grarak.kerneladiutor
but there is a warning that the upstream code is not totally free.

**Comment by Tony-il-Capo** [comment]
There's a [fork](https://github.com/NHellFire/KernelAdiutor) with all non free libraries removed 

And it's already on [F-Droid](https://f-droid.org/packages/com.nhellfire.kerneladiutor/)

**Comment by nazar-pc** [comment]
I've installed it already, but there are some issues with that fork:
* it fails to apply settings on boot (Android shows that app crashed and suggests to disable it until reboot)
* it fails to change icon to material (app crashes, disappears from the apps list and never shows up again until complete removal and re-installation)

Also fork doesn't have issues enabled, so I wasn't able to report issue there. Maybe I'll just ping @NHellFire here.

**Comment by NHellFire** [comment]
Issues are disabled by default on forks. I'll enable them when I'm back at
my laptop.

Those crashes are actually @grarak's fault. That code assumes the class
names will always match the package name (they don't have to and I didn't
change them, otherwise I'll have to edit and rename every single file).
I've tagged a new release with that fixed.


On 25 Oct 2017 14:52, "Nazar Mokrynskyi" <notifications@github.com> wrote:

I've installed it already, but there are some issues with that fork:

   - it fails to apply settings on boot (Android shows that app crashed and
   suggests to disable it until reboot)
   - it fails to change icon to material (app crashes, disappears from the
   apps list and never shows up again until complete removal and
   re-installation)

Also fork doesn't have issues enabled, so I wasn't able to report issue
there. Maybe I'll just ping @NHellFire <https://github.com/nhellfire> here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Grarak/KernelAdiutor/issues/545#issuecomment-339336940>,
or mute the thread

**Comment by nazar-pc** [comment]
Thanks, @NHellFire! I think you can submit a PR upstream in order to fix the issue and have a smaller delta in your fork.
Closing this now, since fork is also fine for me.

**Comment by Tony-il-Capo** [comment]
> - it fails to apply settings on boot (Android shows that app crashed and suggests to disable it until reboot)
> - it fails to change icon to material (app crashes, disappears from the apps list and never shows up again until complete removal and re-installation)

Yes, I can confirm these issues with the fork.
I see that some work has already been done to fix this.
Thanks.

**Comment by guest4711** [comment]
Yes, the fork has this issue. But thanks for forking and distributing it in f-droid.
