### ISSUE TITLE
Apply On Boot

### ISSUE THREAD

**Issue by KrapK** [Grarak/KernelAdiutor#549]
Apply on Boot doesn't work in Android O, App crashes after booting up.

**Comment by substanceof** [comment]
Same on 7.1.1 (los). Crash happens before the apply-on-boot timeout starts. 
Logcat:
```
java.lang.RuntimeException: Unable to start service com.grarak.kerneladiutor.services.boot.Service@f4b41e9 with Intent { cmp=com.nhellfire.kerneladiutor/com.grarak.kerneladiutor.services.boot.Service }: java.lang.IllegalArgumentException: Component class com.nhellfire.kerneladiutor.activities.StartActivity-Material does not exist in com.nhellfire.kerneladiutor
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3368)
  ...
```

**Comment by mobspyguy** [comment]
Can confirm this issue like substanceof wrote.

**Comment by Tony-il-Capo** [comment]
Same problem on old Android 4.1.2. 'Script mode' crashes too.
Tested on a Xperia S.

**Comment by lss4** [comment]
The issue is for the F-Droid version and has been confirmed.

While NHellFire has corrected it in his repo and tagged for another release, it's still unknown when this version will be available on F-Droid.

**Comment by figue** [comment]
Tried to build latest version because KA fails to load on boot. It seems broken yet. Logcat shows:

`11-23 16:29:00.999   750  1926 I ActivityManager: Start proc 2748:com.grarak.kerneladiutor/u0a137 for broadcast com.grarak.kerneladiutor/.services.boot.Receiver
11-23 16:29:01.006  2748  2748 I zygote  : Late-enabling -Xcheck:jni
11-23 16:29:01.246  2748  2748 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
11-23 16:29:01.617  2748  2748 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-23 16:29:01.644  2748  2748 I FA      : App measurement is starting up, version: 9683
11-23 16:29:01.644  2748  2748 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
11-23 16:29:01.689  2748  2748 I FA      : To enable faster debug mode event logging run:
11-23 16:29:01.689  2748  2748 I FA      :   adb shell setprop firebase.analytics.debug-mode com.grarak.kerneladiutor
11-23 16:29:01.705  2748  2748 I FirebaseInitProvider: FirebaseApp initialization successful
11-23 16:29:01.719   750  1942 W ActivityManager: Background start not allowed: service Intent { cmp=com.grarak.kerneladiutor/.services.boot.Service } to com.grarak.kerneladiutor/.services.boot.Service from pid=2748 uid=10137 pkg=com.grarak.kerneladiutor
11-23 16:29:01.731  2748  2748 D AndroidRuntime: Shutting down VM
11-23 16:29:01.744  2748  2748 E AndroidRuntime: FATAL EXCEPTION: main
11-23 16:29:01.744  2748  2748 E AndroidRuntime: Process: com.grarak.kerneladiutor, PID: 2748
11-23 16:29:01.744  2748  2748 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.grarak.kerneladiutor.services.boot.Receiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.grarak.kerneladiutor/.services.boot.Service }: app is in background uid UidRecord{62e0aee u0a137 RCVR idle procs:1 seq(0,0,0)}
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3280)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6562)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.grarak.kerneladiutor/.services.boot.Service }: app is in background uid UidRecord{62e0aee u0a137 RCVR idle procs:1 seq(0,0,0)}
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1514)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1470)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:644)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:644)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at com.grarak.kerneladiutor.services.boot.Receiver.onReceive(Receiver.java:37)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3273)
11-23 16:29:01.744  2748  2748 E AndroidRuntime: 	... 8 more`

**Comment by Tony-il-Capo** [comment]
[This fork](https://github.com/NHellFire/KernelAdiutor) have this fixed some time ago.
Remember that
> This is a mirror with tagged versions and non-free libraries removed. 

[F-Droid](https://f-droid.org/packages/com.nhellfire.kerneladiutor/)

**Comment by figue** [comment]
No, that fork doesn't work, either F-Droid. Confirmed both.

**Comment by Tony-il-Capo** [comment]
> No, that fork doesn't work, either F-Droid. Confirmed both.

That works for me, I was getting app crashes after boot before the last update, now, not anymore.
Maybe you problem is different, probably related to the use Oreo ROM.

**Comment by figue** [comment]
Yes, should be that. Any thoughts how to fix boot in Oreo?

**Comment by Tony-il-Capo** [comment]
Sorry, none.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/18c9e70a2e76c648e5e4231f9957d0bc0a18cfdf

**Comment by figue** [comment]
Saw it. Thank you @Grarak

**Comment by figue** [comment]
Still fails at boot:

https://privatebin.net/?44936b6fa6392b5d#lAr7GUO03VRbKxD0b2uzSc67/4hmA24OqkJIKR91/m4=

**Comment by Grarak** [comment]
Are you sure you got the latest version? Lines don't match with code in your logcat.

**Comment by figue** [comment]
Sorry, wrong logcat. Here's a new one:
https://privatebin.net/?728a2627d612ab67#MT3CQ1MbmV8XxyRXqNHczLKu98ydpHZBde6WKe9Fw7M=

Confirmed: did a "git pull" and Android reports 0.9.73.2

**Comment by figue** [comment]
That's really odd, sometimes KA apply on boot suddenly, no reboot, it's like some kind of "trigger". Happened 2 o 3 times today. Finally I could get a logcat:

https://privatebin.net/?040d4fb435228dbb#RiafrwkBv07tI+vhZmM01vFMNDYnwSR5GOKiKO5yub4=

**Comment by ready34** [comment]
I got figue's issue too, sometimes Kernel Adiutor beeping and I see notification like "Applyng On Boot Setting" although I didn't rebooting my phone.

[logcat.txt](https://github.com/Grarak/KernelAdiutor/files/1503581/logcat.txt)

**Comment by Grarak** [comment]
This should fix it once and for all 
https://github.com/Grarak/KernelAdiutor/commit/eeca69a1fe8de920832fb54a1f49e0128b7a4067

**Comment by figue** [comment]
Thanks Garak. Force close on boot is gone for me with 0.9.73.3 and settings were applied correctly. Will report if I see something else.
