### ISSUE TITLE
Cannot change the maximum and minimum CPU frequency

### ISSUE THREAD

**Issue by gunine** [Grarak/KernelAdiutor#63]
I am using the Galaxy S5 with customized kernel.
With CPUSet application I can change the maximum and minimum CPU frequency in online manner,
but when I change to use KernelAdiutor to set the CPU frequency, it will be reset as the default value.

**Comment by Punchieo** [comment]
Sometimes the max and min freqs ave a mind of their own on the g3

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/7483b1bdc6add8ff7f860d76e903e90475c68aa8

**Comment by avently** [comment]
This issue is actual. I am getting problems with max freq. It selected on 1300 in app, but only 819 work. It just stays on 819, but max is 1300. Every core shows only 819. When i found this post i tryed to change permissions on random files in cpu & cpu0 folders and set it to 444. Now everything is work correctly. I think Kernel Adiutor has a wrong piece of code somewhere. I use the latest version from Play Market. Can you fix it?
